FSTAR_HOME := $(shell $(FSTAR_EXE) --locate)/..
include $(FSTAR_HOME)/../.common.mk # Fixme
FSTAR_ULIB=$(shell $(FSTAR_EXE) --locate_lib)
include $(FSTAR_HOME)/gmake/fstar.mk

# we ignore the return result in benchmark runs because we can have micro-benchmarks which
# produce error asserts when executed with '--admit_smt_queries true'
%.uver: %.fst
	$(Q)$(BENCHMARK_PRE) $(FSTAR)  $^

%.fail-uver: %.fst
	(! $(FSTAR) $^ >/dev/null 2>&1) || (echo "NEGATIVE TEST FAILED ($@)!" ; false)
