name: Build F* and test related projects
on:
  push:
  workflow_dispatch:

# TODO:
# Is there a way to set the default container? this is stupid
# Move to the regular fstar-ci-base too

defaults:
  run:
    # Setting the default shell to bash. This is not only more standard,
    # but also makes sure that we run with -o pipefail, so we can safely
    # pipe data (such as | tee LOG) without missing out on failures
    # and getting false positives. If you want to change the default shell,
    # keep in mind you need a way to handle this.
    shell: bash

jobs:
  fstar-build:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV


      - uses: actions/checkout@master
        with:
          path: FStar/

      - name: Prep
        run: |
          # In case we edited fstar.opam, install new deps here
          opam install --confirm-level=unsafe-yes --deps-only ./FStar/fstar.opam

      - run: find
      - run: env
      - run: pwd
      - run: touch IM_HERE

      - name: Build
        run: |
          export ADMIT=1 # faster testing
          eval $(opam env)
          make -C FStar -skj$(nproc) ADMIT=1

      - name: Tar for artifact
        run: tar -cvf FStar.tar --exclude FStar/.git --exclude FStar/ocaml FStar

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          path: FStar.tar
          name: FStar
          retention-days: 1 # revisit

  fstar-test:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs: fstar-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV

      - run: find

      - name: Test
        run: |
          eval $(opam env)
          make -C FStar -skj$(nproc) ci-uregressions

  fstar-test-boot:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs: fstar-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV

      - run: find

      - name: Bootstrap
        run: |
          eval $(opam env)
          make -C FStar -skj$(nproc) full-bootstrap

      - name: Check
        run: |
          echo "git status:"
          git status
          FAILED=false
          if ! git diff --exit-code ocaml/; then
            echo "::group::DIFF"
            git diff
            echo "::endgroup::"
            FAILED=true
          fi
          if git ls-files --others --exclude-standard -- ocaml/ | grep -q; then
            echo "::group::EXTRA FILES"
            git diff
            echo "::endgroup::"
            FAILED=true
          else
          if $FAILED; then false; fi

  krml-build:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs: fstar-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV

      - name: Clone karamel
        uses: actions/checkout@master
        with:
          path: karamel/
          repository: FStarLang/karamel

      - run: find

      - name: Build krml
        run: |
          eval $(opam env)
          make -C karamel -skj$(nproc)

      - name: Tar for artifact
        run: tar -cvf karamel.tar --exclude karamel/.git karamel

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          path: karamel.tar
          name: karamel
          retention-days: 1 # revisit
      
  krml-test:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs:
      - fstar-build
      - krml-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - name: Get karamel
        uses: actions/download-artifact@master
        with:
          name: karamel
          path: .
      - name: Untar
        run: tar xf karamel.tar

      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV
      - run: echo "KRML_HOME=$(pwd)/karamel" >> $GITHUB_ENV

      - run: find

      - name: Test
        run: |
          # Will fail due to rust
          eval $(opam env)
          make -C karamel -skj$(nproc) test

  steel-build:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs:
      - fstar-build
      - krml-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - name: Get karamel
        uses: actions/download-artifact@master
        with:
          name: karamel
          path: .
      - name: Untar
        run: tar xf karamel.tar

      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV
      - run: echo "KRML_HOME=$(pwd)/karamel" >> $GITHUB_ENV

      - run: find

      - name: Clone steel
        uses: actions/checkout@master
        with:
          path: steel/
          repository: FStarLang/steel

      - run: find

      - name: Build
        run: |
          eval $(opam env)
          make -C steel -skj$(nproc)

      - name: Tar for artifact
        run: tar -cvf steel.tar --exclude steel/.git steel

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          path: steel.tar
          name: steel
          retention-days: 1 # revisit

  pulse-build:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs:
      - fstar-build
      - krml-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - name: Get karamel
        uses: actions/download-artifact@master
        with:
          name: karamel
          path: .
      - name: Untar
        run: tar xf karamel.tar

      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV
      - run: echo "KRML_HOME=$(pwd)/karamel" >> $GITHUB_ENV

      - run: find

      - name: Clone pulse
        uses: actions/checkout@master
        with:
          path: pulse/
          repository: FStarLang/pulse

      - run: find

      - name: Build
        run: |
          eval $(opam env)
          make -C pulse -skj$(nproc)

      - name: Tar for artifact
        run: tar -cvf pulse.tar --exclude pulse/.git pulse

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          path: pulse.tar
          name: pulse
          retention-days: 1 # revisit

  hacl-build:
    runs-on: [linux, X64]
    container: mtzguido/fstar-base-testing
    needs:
      - fstar-build
      - krml-build
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV

      - name: Get FStar
        uses: actions/download-artifact@master
        with:
          name: FStar
          path: .
      - name: Untar
        run: tar xf FStar.tar
      - name: Get karamel
        uses: actions/download-artifact@master
        with:
          name: karamel
          path: .
      - name: Untar
        run: tar xf karamel.tar

      - run: echo "FSTAR_HOME=$(pwd)/FStar" >> $GITHUB_ENV
      - run: echo "KRML_HOME=$(pwd)/karamel" >> $GITHUB_ENV

      - run: find

      - name: Clone hacl-star
        uses: actions/checkout@master
        with:
          path: hacl-star/
          repository: hacl-star/hacl-star

      - name: Get Vale
        run: ./tools/get_vale.sh

      - run: find

      - name: Build
        run: |
          eval $(opam env)
          make -C hacl-star -skj$(nproc)

      - name: Tar for artifact
        run: tar -cvf hacl-star.tar --exclude hacl-star/.git hacl-star

      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          path: hacl-star.tar
          name: hacl-star
          retention-days: 1 # revisit
