name: FStar build and test

on:
  push:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-fstar:
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: make -skj$(nproc) |& .scripts/format_for_github_actions.sh

      - name: Package
        run: make -skj$(nproc) package |& .scripts/format_for_github_actions.sh

      - name: Upload package as build artifact
        uses: actions/upload-artifact@v4
        with:
          path: fstar.tar.gz
          name: fstar.tar.gz
          retention-days: 3

      - name: Test
        run: make -skj$(nproc) test |& .scripts/format_for_github_actions.sh

  test-package:
    needs: build-fstar
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master
      # ^ z3 is installed in the OPAM switch. We should probably get it
      # from elsewhere and *not* use this container so we separate the
      # runtime requirements from build requirements.

      - name: Get fstar package
        uses: actions/download-artifact@v4
        with:
          name: fstar.tar.gz

      - run: tar xzf fstar.tar.gz

      - name: Smoke test
        run: ./bin/fstar.exe ulib/Prims.fst -f
