name: FStar build and test

on:
  push:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-fstar:
    # Build an F* binary package: a fully-bootstrapped stage 2 compiler,
    # with its plugins, a fully checker library (i.e. with .checked) files
    # and compiled versions of fstar_lib and fstar_plugin_lib.
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      - name: Checkout
        uses: actions/checkout@master

      - name: Build and package
        run: make -skj$(nproc) package

      - name: Upload package as build artifact
        uses: actions/upload-artifact@v4
        with:
          path: fstar.tar.gz
          name: fstar.tar.gz
          retention-days: 3

  test:
    # Download the binary package from the previous job and run the tests
    # in the repo. This makes sure that the tests do not depend on some
    # random internal state of the repo, but only on out/.
    #
    # We could be paranoid and rm -rf ulib too, it should not make a difference.
    needs: build-fstar
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      - name: Checkout
        uses: actions/checkout@master

      - name: Get fstar package
        uses: actions/download-artifact@v4
        with:
          path: fstar.tar.gz
          name: fstar.tar.gz

      - name: Set up package locally
        run:
          mkdir out
          tar xzf fstar.tar.gz -C out

      - name: Run tests
        run: make -skj$(nproc) test

  test-external:
    # Download the binary package into a fresh machine and
    # test that it starts up. Note: this does not check out the repo,
    # this is meant to mimic a normal user of the binary package.
    needs: build-fstar
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master
      # ^ z3 is installed in the OPAM switch. We should probably get it
      # from elsewhere and *not* use this container so we separate the
      # runtime requirements from build requirements.

      - name: Get fstar package
        uses: actions/download-artifact@v4
        with:
          name: fstar.tar.gz

      - run: tar xzf fstar.tar.gz

      - name: Smoke test
        run: ./bin/fstar.exe ulib/Prims.fst -f

  test-stage1:
    # Run all tests over the stage 1 compiler. They should all pass,
    # just like for stage2. The compiler used to build fstar.exe should
    # not matter.
    runs-on: ubuntu-latest
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      - name: Checkout
        uses: actions/checkout@master

      - name: Build stage 1
        run: make -skj$(nproc) 1
      - name: Run tests
        run: make -skj$(nproc) test
