name: F* nightly build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-all:
    uses: ./.github/workflows/build-all.yml

  publish:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: fstar-Linux-x86_64.tar.gz
      - uses: actions/download-artifact@v4
        with:
          name: fstar-src.tar.gz
      - uses: actions/download-artifact@v4
        with:
          name: fstar-Darwin-x86_64.tar.gz

      - name: Publish artifacts in nightly tag
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nigthly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            fstar-Linux-x86_64.tar.gz
            fstar-Darwin-x86_64.tar.gz
            fstar-src.tar.gz
