name: F* nightly build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: fstar-ci.tar.gz
      - uses: actions/download-artifact@v4
        with:
          name: fstar-ci-src.tar.gz

      - name: Publish artifacts in nightly tag
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nigthly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            fstar-ci.tar.gz
            fstar-ci-src.tar.gz
