name: F* nightly build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-all:
    uses: ./.github/workflows/build-all.yml

  publish:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - name: Set up git
        run: |
          git config --global user.name "Dzomo, the Everest Yak"
          git config --global user.email "24394600+dzomo@users.noreply.github.com"

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          # ^ Download all artifacts into the same dir.
          # Each of them is a single file, so no clashes happen.

      - name: Publish artifacts in nightly tag
        run: |
          # try to create the release, then upload
          REPO="${{github.repository}}-nightly" # We push nightly builds to a different repo
          TAG=nightly-$(date -I)
          git tag $TAG ${{github.sha}}
          git push https://github.com/$REPO.git $TAG
          gh release create -R "$REPO" \
            --generate-notes \
            --target ${{github.sha}} \
            $TAG artifacts/fstar-*
        env:
          GH_TOKEN: ${{ github.token }}
