name: F* CI
on:
  pull_request:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-fstar:
    runs-on: [self-hosted]
    container: mtzguido/fstar-base-testing
    steps:
      - name: Cleanup
        run: find . -delete
      - run: echo "HOME=/home/opam" >> $GITHUB_ENV
      - uses: mtzguido/set-opam-env@master

      - name: Checkout
        uses: actions/checkout@master
        with:
          path: FStar/

      - name: Checkout karamel
        uses: actions/checkout@master
        with:
          path: karamel/
          repository: FStarLang/karamel

      - run: |
          echo KRML_HOME=$(pwd)/karamel >>$GITHUB_ENV
          echo FSTAR_CI_TEST_KARAMEL=1  >>$GITHUB_ENV

      - name: Build
        run: make -C FStar -skj$(nproc) ci

      - name: Check for snapshot diff
        run: ./.scripts/check-snapshot-diff.sh
