name: Create F* release and publish

on:
  workflow_dispatch:

jobs:
  # Bump version number beforehand? I don't think the action can push
  # that to master (easily). Just remember to do so manually.

  build-all:
    uses: ./.github/workflows/build-all.yml

  publish:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: fstar-Linux-x86_64.tar.gz
      - uses: actions/download-artifact@v4
        with:
          name: fstar-src.tar.gz
      - uses: actions/download-artifact@v4
        with:
          name: fstar-Darwin-x86_64.tar.gz

      - uses: actions/checkout@v4
        with:
          path: FStar
      - name: Rename packages to have version number
        run: |
          V="v$(cat FStar/version.txt)"
          for file in fstar-*.tar.gz; do
            mv "$file" "${file/fstar-/fstar-$V-}"
          done

      - name: Publish release
        run: |
          V=$(cat FStar/version.txt)
          git tag -a "v$V" -m "F* version $V"
          git push origin "v$V"
          gh release create --prerelease \
            --generate-notes \
            -t "F* v$V" \
            "v$V" fstar-*.tar.gz
